######################################################################
# Automatically generated by qmake (2.01a) jeu. janv. 30 17:24:00 2014
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += wheel.hpp \
           ../../src/modules/encoder.hpp \
           ../../src/modules/modules.hpp \
           ../../src/modules/motor_wheel.hpp \
           ../../src/modules/servo.hpp
SOURCES += test_modules.cpp \
           wheel.cpp \
           ../../src/modules/encoder.cpp \
           ../../src/modules/modules.cpp \
           ../../src/modules/motor_wheel.cpp \
           ../../src/modules/servo.cpp
