######################################################################
# Automatically generated by qmake (3.0) dim. févr. 16 11:48:39 2014
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
