######################################################################
# Automatically generated by qmake (2.01a) sam. févr. 1 14:49:00 2014
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += modules.hpp  servo.hpp balise.hpp RDS.hpp
SOURCES += modules.cpp  servo.cpp balise.cpp RDS.cpp
