######################################################################
# Automatically generated by qmake (2.01a) sam. févr. 1 14:49:00 2014
######################################################################

TEMPLATE = app
TARGET = servo
DEPENDPATH += .
INCLUDEPATH += . /usr/include/bullet

QMAKE_CXXFLAGS = -std=c++11
LIBS += -lBulletDynamics -lBulletCollision -lLinearMath -L/usr/local/lib

# Input
HEADERS += balise.hpp
SOURCES += balise.cpp
